import React from "react";
import "../style/About.css";

const About = () => {
  return (
    <section className="about-section">
      <div className="about-container">
        {/* <div className="about-image">
          <img
            src="https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80"
            alt="About Us"
          />
        </div> */}

        <div className="about-content">
          <h2> About Our Travel Planner</h2>
          <p>
            Welcome to <strong>Travel.ai</strong> — your AI-powered travel companion.
            We help explorers like you discover the perfect destinations, plan
            memorable itineraries, and make every journey stress-free.
          </p>
          <p>
            Our goal is simple: to make travel planning effortless and inspiring.
            Whether you love beaches, adventure, culture, or food — we use smart
            recommendations and real-time data to craft trips tailored to your
            interests and mood.
          </p>

          <div className="about-highlights">
            <div className="highlight-card">
              <h3> Personalized Itineraries</h3>
              <p>
                Get curated travel plans generated by AI — customized to your
                budget, preferences, and style.
              </p>
            </div>
            <div className="highlight-card">
              <h3> Live Weather & Insights</h3>
              <p>
                Check real-time conditions before you go — and always be ready
                for the perfect travel moment.
              </p>
            </div>
            <div className="highlight-card">
              <h3>Smart Suggestions</h3>
              <p>
                Discover unique experiences and hidden gems you might otherwise
                miss, all powered by AI and curated data.
              </p>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
};

export default About;
